services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=ny_taxi 
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ny_taxi
    volumes:
      - "/home/jamiu/Documents/ny_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=jmoh.tunde@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
  ingest:
    build: .
